# Generated by Django 4.1.1 on 2022-09-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('idhistoria', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(max_length=45, verbose_name='Sugerencia')),
                ('diagnostico', models.CharField(max_length=45, verbose_name='Diagnostico')),
                ('entorno', models.CharField(max_length=45, verbose_name='Entorno')),
                ('fecha', models.DateField(max_length=45, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=45, verbose_name='Nombre')),
                ('fecha_nac', models.CharField(max_length=45, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=10, verbose_name='Telefono')),
                ('idhistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.historia')),
            ],
        ),
        migrations.CreateModel(
            name='personalSalud',
            fields=[
                ('idpersonal_salud', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=45, verbose_name='Especialidad')),
                ('registro', models.CharField(max_length=45, verbose_name='Registro Médico')),
                ('rol', models.CharField(max_length=45, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('genero', models.CharField(max_length=45, verbose_name='Género')),
                ('perfil', models.CharField(max_length=45, verbose_name='Perfil')),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='authApp.paciente')),
                ('idpersonal_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='authApp.personalsalud')),
            ],
        ),
        migrations.CreateModel(
            name='Signos',
            fields=[
                ('idsignos', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.IntegerField(default=0, verbose_name='Oximetria')),
                ('frec_cardiaca', models.IntegerField(default=0, verbose_name='Frecuencia Cardiaca')),
                ('frec_respiratoria', models.IntegerField(default=0, verbose_name='Frecuencia Respiratoria')),
                ('temperatura', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Temperatura')),
                ('presion_arterial', models.IntegerField(default=0, verbose_name='Presión Arterial')),
                ('glicemias', models.CharField(max_length=45, verbose_name='Glicemias')),
                ('fecha', models.DateTimeField(max_length=45, verbose_name='Glicemias')),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos', to='authApp.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='idpersonal_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authApp.personalsalud'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('idfamiliar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=45, verbose_name='Parentesco')),
                ('correo', models.CharField(max_length=45, verbose_name='Correo')),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='authApp.paciente')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='authApp.usuario')),
            ],
        ),
    ]
